name: crypto-lens-small

services:
  cl_s_app:
    container_name: cl_s_app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./logs:/root/logs
